title: VPN购买指南
baseurl: /
permalink: /:title/
domain: https://vpnpays.com
layout_type: boxed
style: classic
palette: gray
mode: light
base_font: serif
header:
  primary_nav_links:
    - type: action
      label: Blog
      url: /blog
      style: link
  has_primary_nav: true
  anncmnt_has_close: true
  anncmnt_is_home_only: true
  anncmnt_id: new-features
  logo: images/classic/logo.svg
  anncmnt_content: Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien.
    **[Learn More](/pricing/)**
  has_anncmnt: true
  secondary_nav_links:
    - type: action
      label: Contact
      url: /contact
      style: link
    - type: action
      label: Get Started
      url: /pricing
      style: primary
  has_secondary_nav: true
  logo_alt: DIY logo
  anncmnt_align: left
  title: DIY
  type: header
footer:
  primary_nav_links:
    - type: action
      label: About
      url: /about
      style: link
    - type: action
      label: Style Guide
      url: /style-guide
      style: link
  has_primary_nav: true
  social_links:
    - style: link
      has_icon: false
      icon_position: right
      new_window: false
      no_follow: false
      type: action
      url: Twitter.com
      label: Twitter
  logo: images/classic/logo.svg
  tertiary_nav_title: Legal
  tertiary_nav_links:
    - type: action
      label: Terms & Conditions
      url: /terms-conditions
      style: link
    - type: action
      label: Privacy Policy
      url: /privacy-policy
      style: link
  secondary_nav_title: Blog
  secondary_nav_links:
    - type: action
      label: News
      url: /blog/category/news
      style: link
    - type: action
      label: General
      url: /blog/category/general
      style: link
    - type: action
      label: Tutorials
      url: /blog/category/tutorials
      style: link
  has_social: true
  has_secondary_nav: true
  logo_alt: DIY logo
  content: '&copy; Stackbit. All rights reserved. This Jamstack site was created
    with <a href="https://www.stackbit.com/?utm_source=deployed-footer"
    target="_blank" rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=diy&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>'
  type: footer
  has_tertiary_nav: true
  primary_nav_title: Company
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: /posts/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
