title: VPN购买指南
baseurl: /
permalink: /:title/
domain: https://vpnpays.com
layout_type: boxed
style: classic
palette: gray
mode: light
base_font: serif
header:
  primary_nav_links:
    - type: action
      label: Blog
      url: /blog
      style: link
    - style: link
      has_icon: false
      icon_position: right
      new_window: false
      no_follow: false
      type: action
      label: VPN评测
      url: /reviews
  has_primary_nav: true
  anncmnt_has_close: true
  anncmnt_is_home_only: true
  anncmnt_id: new-features
  logo: images/classic/logo.svg
  anncmnt_content: 累计评测了1091款VPN. [查看推荐](vpnpays.com/reviews)
  has_anncmnt: true
  secondary_nav_links: []
  has_secondary_nav: true
  logo_alt: VPNPays
  anncmnt_align: left
  title: VPN购买指南
  type: header
footer:
  primary_nav_links:
    - type: action
      label: About
      url: /about
      style: link
  has_primary_nav: true
  social_links:
    - url: Twitter.com
      icon_position: right
      new_window: false
      no_follow: false
      style: link
      label: Twitter
      icon: twitter
      type: action
      has_icon: true
  logo: images/classic/logo.svg
  tertiary_nav_title: Legal
  tertiary_nav_links:
    - type: action
      label: Terms & Conditions
      url: /terms-conditions
      style: link
    - type: action
      label: Privacy Policy
      url: /privacy-policy
      style: link
  secondary_nav_title: Blog
  secondary_nav_links:
    - type: action
      label: News
      url: /blog/category/news
      style: link
    - type: action
      label: General
      url: /blog/category/general
      style: link
    - type: action
      label: Tutorials
      url: /blog/category/tutorials
      style: link
  has_social: true
  has_secondary_nav: true
  logo_alt: VPN指南logo
  content: "&copy; VPNPays. All rights reserved. "
  links: []
  type: footer
  has_tertiary_nav: true
  primary_nav_title: VPNPays
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: /posts/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
